### PR TITLE
Define Oro Contact 'firstName' field as filter and sorter in OroCRM JSON API, to be compatible with Brazilian use of names

### PR DESCRIPTION
**Pull request by pedrofurtado**
Based on #306 .

In Brazil, it's very common to search, filter and sort the contacts by first name. Because of that, Oro should be compatible with this type of use of names. I've created a micro bundle for this (https://github.com/pedrofurtado/orocrm-firstname-api-bundle), but it's much better if this feature is included by default in OroCRM.

Thanks!

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by pedrofurtado** [comment]
Any news?

**Comment by pedrofurtado** [comment]
I am signed in CLA now :+1:

**Comment by anyt** [comment]
There is no need to update api configuration as field will be added automatically to filters in case it has index

**Comment by pedrofurtado** [comment]
@anyt If so, I make this change quickly. Then, if the code of PR is fine, it can be merged. 🥇

**Comment by anyt** [comment]
Hi @pedrofurtado ,
Sorry for a long response, we have some discussion in a dev team about necessity to add an index here as not all applications need it.
But the contact table can contain millions of records and index can slow down insert operations to that table. 

And from the other side it can be easily added on customization side.

**Comment by anyt** [comment]
About the src/Oro/Bundle/ContactBundle/Resources/config/oro/api.yml it's just a notice from me as it's enough to have one option, index or api configuration, but you don't need to have both.

**Comment by pedrofurtado** [comment]
@anyt But do you think that is better to create the index or just add a api configuration (without index)? The first option improves performance but adds a overhead in insertions, and the second option looses in performance but not add overhead in insertions.

**Comment by pedrofurtado** [comment]
@anyt As soon as possible, send me a feedback and then I will make the changes suggested in PR 👍

**Comment by anyt** [comment]
As contacts table is not updated frequently and first name variations are quite big - adding firstName index only improves system performance.
But configuration for API should be deleted, as filter will be added automatically based on index.

**Comment by pedrofurtado** [comment]
@anyt Configuration for API deleted, as suggested 👍

**Comment by anyt** [comment]
Merged to master branch. 
Thank you for the contribution!

**Pull request closed without merging**
