### PR TITLE
Add Extended fields synchronisation during lead conversion. Fix #226

### LINKED ISSUE #226: Custom fields synchronisation during lead conversion
Hello Artem,

When a custom entity field exist on a Lead and on an Account or Contact for example, is there a mecanism to set the related field value ?  

The mechanism exists for a defined set of fields, but can it be applied also to extended proprieties ?
https://github.com/orocrm/crm/blob/5a23255d0f15b5ae42e5aa07b3c0716201ae55ba/src/Oro/Bundle/SalesBundle/Provider/LeadToOpportunityProvider.php#L74 

Thanks,
Samuel

### PR DESCRIPTION
**Pull request by sadortun**
Hi Oro Team,

This is an attemp in implementing the feature described in #226  Instead of copying only a few specifics fields, between the Lead and Contact, all matching fields will be copied.

Please review before using,I have not touch the Oro internals, it would be fairly possible that some validation are missing ! 

Thanks,
Samuel

### CODE REVIEW

**Comment by manowark** [comment]
Please, fix code styles and failed unit tests.

**Comment by sadortun** [comment]
Hi @manowark  Sure, i'll update the tests too ! 

Quick question, i've noticed in many tests, the `$actual` and `$expected` parameters are inverted in asserts. Any reason why ?
- https://github.com/sadortun/crm/blob/04e18aa795d06ec0cb5a8227642b488f256c5f9c/src/Oro/Bundle/SalesBundle/Tests/Unit/Provider/LeadToOpportunityProviderTest.php#L76

**Comment by manowark** [comment]
Please, just use signature of phpunit methods. In your example $expected should be as first parameter.

**Comment by manowark** [comment]
@sadortun, and please, if you can, give more information about todo that you left in pull request.

**Comment by sadortun** [comment]
@manowark for the remaining to-do,  I was not sure in what action to take. 

If the Lead and  Contact both have an enum, but the enumerated doesn't have the same values, ....
- should you copy the value even if it was not defined ?
- should you skip this field ? 

For example `Lead:: $source`  and `Contact:: $source` 

Currently the value is copied.

**Comment by alexandr-parkhomenko** [comment]
Hello @sadortun,

I think logic that do copy values `enum`, `multiEnum` should be removed. This functionality brings implicit restrictions to naming of  `enum`, `multiEnum` fields and can bring a lot of bugs. We can add extend point where you can merge aditional fields that you want set to Contact. 

Do you agree with my point ?

**Comment by sadortun** [comment]
@alexandr-parkhomenko  I think the validation should be done on the enumerated `value` ( the visible lable) I don't see how it would bring implicit restrictions or cause bugs.

**Comment by alexandr-parkhomenko** [comment]
@sadortun, In general I have next issue, customer can create select field on Lead and Account with same name, but different business key and he won't know that value from this field will be copied to account. How can we prevent this issue with your solution ? 

Extend point will allow you to add custom mapping instruction on fields that you want to copy.

**Comment by alexandr-parkhomenko** [comment]
Enumerated fields should be copied only if `type`, `relation_type` and `related_entity_name` equals, all other cases should be provided through extend point.

**Comment by mkudelya** [comment]
Hi @sadortun 

I found small typo - excluded_proprieties

**Comment by sadortun** [comment]
Noted. I'll submit fixes next week.

**Comment by alexandr-parkhomenko** [comment]
Hi @sadortun.
What do you think about replacing functionality that you've done to another solution with triggering events on next points ( ready to set `Contact` to `Opportunity`, before we return `Opportunity` from ) that you'll catch at your custom bundle  ?

It allows us to reach next key feature - synchronization between Opportunity and Lead will open to modification.

**Comment by sadortun** [comment]
@alexandr-parkhomenko sure, it would be more flexible ! 

My solution was to provide a fix to this "bug" where not all fields were copied. Having it handled by events would be a nice feature to add. 

The changes in this PR will still need to be included in a event handler by default.

@alexandr-parkhomenko do you have time to implement the event handler and submit a PR on your own ? I'll have time to finish the two requested changes discussed earlier this week, but I'll not have time for more.

Have a good day,
Samuel

**Comment by sadortun** [comment]
@mkudelya @alexandr-parkhomenko  Enums are no longer copied as per https://github.com/orocrm/crm/pull/262#issuecomment-292560335 above

**Comment by alexandr-parkhomenko** [comment]
@sadortun unfortunately, the task with event handler has a low priority, so we do not know when we can begin to implement it. If you have a time you can implement this feature within this PR. It's will be good replacement for current fix implementation.

**Comment by sadortun** [comment]
Sorry, I don't have time at the moment. I still think this implementation is an improvement compared to the existing one. You are in a better position to see if it should be merged or postponed.

Have a good day,
Samuel

**Comment by mbessolov** [comment]
_(internal reference CRM-6997)_

**Pull request closed without merging**
