### PR TITLE
Update CallDirectionProvider.php

### PR DESCRIPTION
**Pull request by UnusefulCoder**
- Minor refactorization on function `getLastActivitiesDateForTarget()`.

### CODE REVIEW

**Comment by anyt** [comment]
Hi @UnusefulCoder, 
Can you please explain the reasons for the refactoring? 

We have a strict code style in the project, that doesn't allow nested ternary operators usage, because it's harder to read then a standard if/else, for most of the developers.

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at https://oroinc.com/b2b-ecommerce/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by UnusefulCoder** [comment]
Hello, @anyt.
On the first commit, there is no need to declare the empty array `$result`, but the nested ternary operator is only to reduce code duplication.

Thanks for your attention.

**Comment by anyt** [comment]
Thank you for the contribution, but as this PR violates our coding standards, decreases the code readability and doesn't add any value for the business logic itself, I'm closing it.

**Pull request closed without merging**
